name = "VI-IGNO"
version = "0.1.0"
description = "Master thesis code"
readme = "README.md"
requires-python = ">=3.9,<3.11.0"
dependencies = [
    "numpy<2.3.0",
    "torch==2.6.0",
    "matplotlib<3.5.0",
    "pandas<2.3.0",
    "scipy>=1.13.1",
    "scienceplots>=2.2.0",
    "tqdm>=4.67.1",
    "tensorboard>=2.20.0",
    "pytest>=8.4.2",
    "h5py==2.9.0"
]
