run_name: darcy_continuous
device: cuda
artifact_root: runs
seed: 10086
problem:
  type: darcy_continuous
  train_data: data/darcy_continuous/smh_train/
  test_data: data/darcy_continuous/smh_test_in/
pretrained: null
training:
  epochs: 10000
  batch_size: 50
  epoch_show: 200
  loss_weights:
    pde: 0.25
    data: 2.0
  standardize_latent: false
  optimizer:
    type: Adam
    lr: 0.001
    weight_decay: 1.0e-06
  scheduler:
    type: CosineAnnealing
    step_size: null
    gamma: null
    patience: null
    factor: null
    total_steps: 10000
    pct_start: null
    anneal_strategy: null
    div_factor: null
    final_div_factor: null
    eta_min: 0.000125
evaluation:
  method: igno
  batch_size: 200
  n_obs: 100
  obs_sampling: random
  snr_db: null
  inversion:
    epochs: 500
    loss_weights:
      pde: 1.0
      data: 1.0
    optimizer:
      type: null
      lr: null
      weight_decay: null
    scheduler:
      type: null
      step_size: null
      gamma: null
      patience: null
      factor: null
      total_steps: null
      pct_start: null
      anneal_strategy: null
      div_factor: null
      final_div_factor: null
      eta_min: null
  results_dir: results
