run_name: darcy_continuous
device: cuda
artifact_root: runs
seed: 10086
problem:
  type: darcy_continuous
  train_data: data/darcy_continuous/smh_train/
  test_data: data/darcy_continuous/smh_test_in/
stages:
- foundation
pretrained: null
dgno:
  epochs: 10000
  batch_size: 50
  epoch_show: 50
  loss_weights:
    pde: 0.25
    data: 2.0
  optimizer:
    type: Adam
    lr: 0.001
    weight_decay: 5.0e-06
  scheduler:
    type: StepLR
    step_size: 2500
    gamma: 0.5
    patience: null
    factor: null
    total_steps: null
    pct_start: null
    anneal_strategy: null
    div_factor: null
    final_div_factor: null
    eta_min: null
nf:
  epochs: 10000
  batch_size: 64
  epoch_show: 400
  optimizer:
    type: Adam
    lr: 0.001
    weight_decay: 0.0
  scheduler:
    type: CosineAnnealing
    step_size: null
    gamma: null
    patience: null
    factor: null
    total_steps: 10000
    pct_start: null
    anneal_strategy: null
    div_factor: null
    final_div_factor: null
    eta_min: 1.0e-05
encoder:
  epochs: 1000
  batch_size: 100
  epoch_show: 100
  freeze_decoder: true
  freeze_nf: true
  loss_weights:
    pde: 0
    data: 0
  optimizer:
    type: Adam
    lr: 0.0001
    weight_decay: 0.0001
  scheduler:
    type: Plateau
    step_size: null
    gamma: null
    patience: 50
    factor: 0.5
    total_steps: null
    pct_start: null
    anneal_strategy: null
    div_factor: null
    final_div_factor: null
    eta_min: null
evaluation:
  method: igno
  batch_size: null
  n_obs: 100
  obs_sampling: random
  snr_db: 25.0
  inversion:
    epochs: 1000
    loss_weights:
      pde: null
      data: null
    optimizer:
      type: null
      lr: null
      weight_decay: null
    scheduler:
      type: null
      step_size: null
      gamma: null
      patience: null
      factor: null
      total_steps: null
      pct_start: null
      anneal_strategy: null
      div_factor: null
      final_div_factor: null
      eta_min: null
  results_dir: results
